### ISSUE TITLE
issue with allPlots(n) working on my new Macbook

### ISSUE THREAD

**Issue by dongyy1148** [JuliaMPC/PrettyPlots.jl#7]
The PrettyPlots package works well on my old Macbook. However, after I added the packages to my new Macbook these days and ran the examples again, I found that the optimize!(n) function worked well, but the allPlots(n) function didn't return my any results and it would terminate the Julia. The detailed error is showed below.
> `julia> allPlots(n)
2018-12-11 16:36:18.107 julia[14260:1292598] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f8d75aafd90
2018-12-11 16:36:18.109 julia[14260:1292598] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f8d75aafd90'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff34ed6571 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff60e83efb objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff34f53ca5 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff34e757fe ___forwarding___ + 1468
	4   CoreFoundation                      0x00007fff34e751b8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x000000013ee9331d TkpInit + 413
	6   libtk8.6.dylib                      0x000000013edeb17e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x000000013b1eaa0f _tkinter_create + 1183
	8   libpython3.7m.dylib                 0x000000012c95f2b9 _PyMethodDef_RawFastCallKeywords + 681
	9   libpython3.7m.dylib                 0x000000012c95f3bd _PyCFunction_FastCallKeywords + 45
	10  libpython3.7m.dylib                 0x000000012ca68c4b call_function + 603
	11  libpython3.7m.dylib                 0x000000012ca5fe45 _PyEval_EvalFrameDefault + 7893
	12  libpython3.7m.dylib                 0x000000012ca5dad9 _PyEval_EvalCodeWithName + 3305
	13  libpython3.7m.dylib                 0x000000012c95e1b1 _PyFunction_FastCallDict + 481
	14  libpython3.7m.dylib                 0x000000012c95fba4 _PyObject_Call_Prepend + 164
	15  libpython3.7m.dylib                 0x000000012c9c75aa slot_tp_init + 298
	16  libpython3.7m.dylib                 0x000000012c9d0ca7 type_call + 295
	17  libpython3.7m.dylib                 0x000000012c95ee73 _PyObject_FastCallKeywords + 691
	18  libpython3.7m.dylib                 0x000000012ca68cb4 call_function + 708
	19  libpython3.7m.dylib                 0x000000012ca5ff6c _PyEval_EvalFrameDefault + 8188
	20  libpython3.7m.dylib                 0x000000012c95ea6e function_code_fastcall + 254
	21  libpython3.7m.dylib                 0x000000012ca68cbe call_function + 718
	22  libpython3.7m.dylib                 0x000000012ca5fe45 _PyEval_EvalFrameDefault + 7893
	23  libpython3.7m.dylib                 0x000000012ca5dad9 _PyEval_EvalCodeWithName + 3305
	24  libpython3.7m.dylib                 0x000000012c95e1b1 _PyFunction_FastCallDict + 481
	25  libpython3.7m.dylib                 0x000000012c95fba4 _PyObject_Call_Prepend + 164
	26  libpython3.7m.dylib                 0x000000012c9615b4 method_call + 36
	27  libpython3.7m.dylib                 0x000000012c95f5b6 PyObject_Call + 246
	28  libpython3.7m.dylib                 0x000000012ca601b5 _PyEval_EvalFrameDefault + 8773
	29  libpython3.7m.dylib                 0x000000012ca5dad9 _PyEval_EvalCodeWithName + 3305
	30  libpython3.7m.dylib                 0x000000012c95e1b1 _PyFunction_FastCallDict + 481
	31  ???                                 0x00000001173674ec 0x0 + 4684412140
	32  ???                                 0x0000000117371803 0x0 + 4684453891
	33  ???                                 0x00000001173719d9 0x0 + 4684454361
	34  ???                                 0x00000001173632ad 0x0 + 4684395181
	35  ???                                 0x0000000140c3fd05 0x0 + 5381553413
	36  ???                                 0x0000000140c3fb3f 0x0 + 5381552959
	37  libjulia.0.6.4.dylib                0x000000010c189632 jl_f__apply + 1218
	38  libjulia.0.6.4.dylib                0x000000010c189acf jl_f__apply_latest + 63
	39  sys.dylib                           0x000000010e56ff5c japi1_invokelatest_31812 + 124
	40  libjulia.0.6.4.dylib                0x000000010c189632 jl_f__apply + 1218
	41  ???                                 0x0000000140c3e311 0x0 + 5381546769
	42  ???                                 0x0000000140c3e476 0x0 + 5381547126
	43  ???                                 0x0000000117349c69 0x0 + 4684291177
	44  ???                                 0x0000000117349da0 0x0 + 4684291488
	45  libpython3.7m.dylib                 0x000000012c95ee73 _PyObject_FastCallKeywords + 691
	46  libpython3.7m.dylib                 0x000000012ca68cb4 call_function + 708
	47  libpython3.7m.dylib                 0x000000012ca5fed6 _PyEval_EvalFrameDefault + 8038
	48  libpython3.7m.dylib                 0x000000012c95ea6e function_code_fastcall + 254
	49  ???                                 0x00000001173674ec 0x0 + 4684412140
	50  ???                                 0x0000000117371803 0x0 + 4684453891
	51  ???                                 0x00000001173719d9 0x0 + 4684454361
	52  ???                                 0x00000001173632ad 0x0 + 4684395181
	53  ???                                 0x0000000140c3ccee 0x0 + 5381541102
	54  ???                                 0x0000000140c3ca34 0x0 + 5381540404
	55  ???                                 0x0000000140c3cb03 0x0 + 5381540611
	56  libjulia.0.6.4.dylib                0x000000010c189632 jl_f__apply + 1218
	57  libjulia.0.6.4.dylib                0x000000010c189acf jl_f__apply_latest + 63
	58  ???                                 0x0000000140c237ee 0x0 + 5381437422
	59  ???                                 0x0000000140c1c7dd 0x0 + 5381408733
	60  ???                                 0x0000000140c1cbfe 0x0 + 5381409790
	61  ???                                 0x0000000140c1a985 0x0 + 5381400965
	62  ???                                 0x0000000140c129b9 0x0 + 5381368249
	63  ???                                 0x0000000140c115b2 0x0 + 5381363122
	64  ???                                 0x0000000140c109d7 0x0 + 5381360087
	65  ???                                 0x0000000140c110e6 0x0 + 5381361894
	66  ???                                 0x0000000140c10741 0x0 + 5381359425
	67  ???                                 0x0000000140c10773 0x0 + 5381359475
	68  libjulia.0.6.4.dylib                0x000000010c191568 do_call + 200
	69  libjulia.0.6.4.dylib                0x000000010c18f625 eval + 885
	70  libjulia.0.6.4.dylib                0x000000010c18f2a1 jl_interpret_toplevel_expr + 49
	71  libjulia.0.6.4.dylib                0x000000010c1a56ea jl_toplevel_eval_flex + 1866
	72  libjulia.0.6.4.dylib                0x000000010c189cef jl_toplevel_eval_in + 527
	73  sys.dylib                           0x000000010e30101a julia_eval_18030 + 10
	74  sys.dylib                           0x000000010e301030 jlcall_eval_18029 + 16
	75  sys.dylib                           0x000000010e387712 julia_eval_user_input_20356 + 594
	76  sys.dylib                           0x000000010e387930 jlcall_eval_user_input_20355 + 16
	77  ???                                 0x00000001172fc6aa 0x0 + 4683974314
	78  ???                                 0x00000001172fc930 0x0 + 4683974960
	79  libjulia.0.6.4.dylib                0x000000010c1959a0 start_task + 352
)
libc++abi.dylib: terminating with uncaught exception of type NSException

signal (6): Abort trap: 6
while loading no file, in expression starting on line 0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 47726447 (Pool: 47719099; Big: 7348); GC: 102`

**Comment by huckl3b3rry87** [comment]
what versions are you using? To see this type:
```
Pkg.status()
```

**Comment by huckl3b3rry87** [comment]
PrettyPlots.jl was recently removed and added to NLOptControl.jl as a module

**Comment by dongyy1148** [comment]
> what versions are you using? To see this type:
> 
> ```
> Pkg.status()
> ```

I am using

> ` - NLOptControl                  0.1.6              0269a566 (dirty)
 - PrettyPlots                   0.0.3
 - VehicleModels                 0.1.4`

**Comment by dongyy1148** [comment]
> PrettyPlots.jl was recently removed and added to NLOptControl.jl as a module

So how can I plot the results now?

**Comment by huckl3b3rry87** [comment]
Given that I know you are just using my packages, delete the .julia folder to delete all of your packages then
```
Pkg.add("NLOptControl")
Pkg.add("MichiganAutonomusVehicles")
```
Then use PrettyPlots through NLOptControl
